// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sniffer_data.proto

package com.a.eye.gemini.sniffer.matcher;

public final class SnifferDataProtos {
  private SnifferDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SnifferDataOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required string req_host = 1;
    /**
     * <code>required string req_host = 1;</code>
     */
    boolean hasReqHost();
    /**
     * <code>required string req_host = 1;</code>
     */
    java.lang.String getReqHost();
    /**
     * <code>required string req_host = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqHostBytes();

    // required string req_requesturl = 2;
    /**
     * <code>required string req_requesturl = 2;</code>
     */
    boolean hasReqRequesturl();
    /**
     * <code>required string req_requesturl = 2;</code>
     */
    java.lang.String getReqRequesturl();
    /**
     * <code>required string req_requesturl = 2;</code>
     */
    com.google.protobuf.ByteString
        getReqRequesturlBytes();

    // required string req_tcp_seq = 3;
    /**
     * <code>required string req_tcp_seq = 3;</code>
     */
    boolean hasReqTcpSeq();
    /**
     * <code>required string req_tcp_seq = 3;</code>
     */
    java.lang.String getReqTcpSeq();
    /**
     * <code>required string req_tcp_seq = 3;</code>
     */
    com.google.protobuf.ByteString
        getReqTcpSeqBytes();

    // required string req_tcp_time = 4;
    /**
     * <code>required string req_tcp_time = 4;</code>
     */
    boolean hasReqTcpTime();
    /**
     * <code>required string req_tcp_time = 4;</code>
     */
    java.lang.String getReqTcpTime();
    /**
     * <code>required string req_tcp_time = 4;</code>
     */
    com.google.protobuf.ByteString
        getReqTcpTimeBytes();
  }
  /**
   * Protobuf type {@code gemini.SnifferData}
   */
  public static final class SnifferData extends
      com.google.protobuf.GeneratedMessageLite
      implements SnifferDataOrBuilder {
    // Use SnifferData.newBuilder() to construct.
    private SnifferData(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private SnifferData(boolean noInit) {}

    private static final SnifferData defaultInstance;
    public static SnifferData getDefaultInstance() {
      return defaultInstance;
    }

    public SnifferData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private SnifferData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              reqHost_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              reqRequesturl_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              reqTcpSeq_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              reqTcpTime_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<SnifferData> PARSER =
        new com.google.protobuf.AbstractParser<SnifferData>() {
      public SnifferData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnifferData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SnifferData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string req_host = 1;
    public static final int REQ_HOST_FIELD_NUMBER = 1;
    private java.lang.Object reqHost_;
    /**
     * <code>required string req_host = 1;</code>
     */
    public boolean hasReqHost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string req_host = 1;</code>
     */
    public java.lang.String getReqHost() {
      java.lang.Object ref = reqHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string req_host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqHostBytes() {
      java.lang.Object ref = reqHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string req_requesturl = 2;
    public static final int REQ_REQUESTURL_FIELD_NUMBER = 2;
    private java.lang.Object reqRequesturl_;
    /**
     * <code>required string req_requesturl = 2;</code>
     */
    public boolean hasReqRequesturl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string req_requesturl = 2;</code>
     */
    public java.lang.String getReqRequesturl() {
      java.lang.Object ref = reqRequesturl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqRequesturl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string req_requesturl = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReqRequesturlBytes() {
      java.lang.Object ref = reqRequesturl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqRequesturl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string req_tcp_seq = 3;
    public static final int REQ_TCP_SEQ_FIELD_NUMBER = 3;
    private java.lang.Object reqTcpSeq_;
    /**
     * <code>required string req_tcp_seq = 3;</code>
     */
    public boolean hasReqTcpSeq() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string req_tcp_seq = 3;</code>
     */
    public java.lang.String getReqTcpSeq() {
      java.lang.Object ref = reqTcpSeq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqTcpSeq_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string req_tcp_seq = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReqTcpSeqBytes() {
      java.lang.Object ref = reqTcpSeq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqTcpSeq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string req_tcp_time = 4;
    public static final int REQ_TCP_TIME_FIELD_NUMBER = 4;
    private java.lang.Object reqTcpTime_;
    /**
     * <code>required string req_tcp_time = 4;</code>
     */
    public boolean hasReqTcpTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string req_tcp_time = 4;</code>
     */
    public java.lang.String getReqTcpTime() {
      java.lang.Object ref = reqTcpTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqTcpTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string req_tcp_time = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReqTcpTimeBytes() {
      java.lang.Object ref = reqTcpTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqTcpTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reqHost_ = "";
      reqRequesturl_ = "";
      reqTcpSeq_ = "";
      reqTcpTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqRequesturl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqTcpSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqTcpTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReqHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getReqRequesturlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getReqTcpSeqBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getReqTcpTimeBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReqHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getReqRequesturlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getReqTcpSeqBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getReqTcpTimeBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code gemini.SnifferData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData, Builder>
        implements com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferDataOrBuilder {
      // Construct using com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        reqRequesturl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        reqTcpSeq_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        reqTcpTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData getDefaultInstanceForType() {
        return com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData.getDefaultInstance();
      }

      public com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData build() {
        com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData buildPartial() {
        com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData result = new com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqHost_ = reqHost_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqRequesturl_ = reqRequesturl_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqTcpSeq_ = reqTcpSeq_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.reqTcpTime_ = reqTcpTime_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData other) {
        if (other == com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData.getDefaultInstance()) return this;
        if (other.hasReqHost()) {
          bitField0_ |= 0x00000001;
          reqHost_ = other.reqHost_;
          
        }
        if (other.hasReqRequesturl()) {
          bitField0_ |= 0x00000002;
          reqRequesturl_ = other.reqRequesturl_;
          
        }
        if (other.hasReqTcpSeq()) {
          bitField0_ |= 0x00000004;
          reqTcpSeq_ = other.reqTcpSeq_;
          
        }
        if (other.hasReqTcpTime()) {
          bitField0_ |= 0x00000008;
          reqTcpTime_ = other.reqTcpTime_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqHost()) {
          
          return false;
        }
        if (!hasReqRequesturl()) {
          
          return false;
        }
        if (!hasReqTcpSeq()) {
          
          return false;
        }
        if (!hasReqTcpTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.a.eye.gemini.sniffer.matcher.SnifferDataProtos.SnifferData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string req_host = 1;
      private java.lang.Object reqHost_ = "";
      /**
       * <code>required string req_host = 1;</code>
       */
      public boolean hasReqHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string req_host = 1;</code>
       */
      public java.lang.String getReqHost() {
        java.lang.Object ref = reqHost_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reqHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string req_host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqHostBytes() {
        java.lang.Object ref = reqHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string req_host = 1;</code>
       */
      public Builder setReqHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        reqHost_ = value;
        
        return this;
      }
      /**
       * <code>required string req_host = 1;</code>
       */
      public Builder clearReqHost() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqHost_ = getDefaultInstance().getReqHost();
        
        return this;
      }
      /**
       * <code>required string req_host = 1;</code>
       */
      public Builder setReqHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        reqHost_ = value;
        
        return this;
      }

      // required string req_requesturl = 2;
      private java.lang.Object reqRequesturl_ = "";
      /**
       * <code>required string req_requesturl = 2;</code>
       */
      public boolean hasReqRequesturl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string req_requesturl = 2;</code>
       */
      public java.lang.String getReqRequesturl() {
        java.lang.Object ref = reqRequesturl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reqRequesturl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string req_requesturl = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReqRequesturlBytes() {
        java.lang.Object ref = reqRequesturl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqRequesturl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string req_requesturl = 2;</code>
       */
      public Builder setReqRequesturl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqRequesturl_ = value;
        
        return this;
      }
      /**
       * <code>required string req_requesturl = 2;</code>
       */
      public Builder clearReqRequesturl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqRequesturl_ = getDefaultInstance().getReqRequesturl();
        
        return this;
      }
      /**
       * <code>required string req_requesturl = 2;</code>
       */
      public Builder setReqRequesturlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqRequesturl_ = value;
        
        return this;
      }

      // required string req_tcp_seq = 3;
      private java.lang.Object reqTcpSeq_ = "";
      /**
       * <code>required string req_tcp_seq = 3;</code>
       */
      public boolean hasReqTcpSeq() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string req_tcp_seq = 3;</code>
       */
      public java.lang.String getReqTcpSeq() {
        java.lang.Object ref = reqTcpSeq_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reqTcpSeq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string req_tcp_seq = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReqTcpSeqBytes() {
        java.lang.Object ref = reqTcpSeq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqTcpSeq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string req_tcp_seq = 3;</code>
       */
      public Builder setReqTcpSeq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqTcpSeq_ = value;
        
        return this;
      }
      /**
       * <code>required string req_tcp_seq = 3;</code>
       */
      public Builder clearReqTcpSeq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqTcpSeq_ = getDefaultInstance().getReqTcpSeq();
        
        return this;
      }
      /**
       * <code>required string req_tcp_seq = 3;</code>
       */
      public Builder setReqTcpSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqTcpSeq_ = value;
        
        return this;
      }

      // required string req_tcp_time = 4;
      private java.lang.Object reqTcpTime_ = "";
      /**
       * <code>required string req_tcp_time = 4;</code>
       */
      public boolean hasReqTcpTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string req_tcp_time = 4;</code>
       */
      public java.lang.String getReqTcpTime() {
        java.lang.Object ref = reqTcpTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reqTcpTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string req_tcp_time = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReqTcpTimeBytes() {
        java.lang.Object ref = reqTcpTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqTcpTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string req_tcp_time = 4;</code>
       */
      public Builder setReqTcpTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        reqTcpTime_ = value;
        
        return this;
      }
      /**
       * <code>required string req_tcp_time = 4;</code>
       */
      public Builder clearReqTcpTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        reqTcpTime_ = getDefaultInstance().getReqTcpTime();
        
        return this;
      }
      /**
       * <code>required string req_tcp_time = 4;</code>
       */
      public Builder setReqTcpTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        reqTcpTime_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gemini.SnifferData)
    }

    static {
      defaultInstance = new SnifferData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gemini.SnifferData)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
